### ISSUE TITLE
Yelo Play not working on Kodi abroad

### ISSUE THREAD

**Issue by Jolle99** [add-ons/plugin.video.yelo#20]
Hello, since yesterday the Yelo Play app doesn't work anymore on Kodi 18.6.
It just keeps loading it seems. Same issue on Kodi 18.6 on different devices (Macbook, Nvidia Shield and Xiaomi box).
Sometimes (not always) it complains about wrong credentials, but I'm sure that the credentials are correct as I used them on a browser as well. In the browser, it also asks for a "are you not a robot" check, maybe that's causing the issue on Kodi now?

Could you look into this please?

**Comment by dagwieers** [comment]
It is still working fine for me. Could this be related to #16 ?

**Comment by Jolle99** [comment]
Hello,
Don't think so, as this is related to the new box from Telenet. We still have just the white modem/router (since last year April), no digibox at all, just the C+ module. It always worked until yesterday or the day before. 

Best regards,

J.

**Comment by dagwieers** [comment]
Ok, I just verified. If you run the master branch this issue appears to be fixed.
@Jolle99 Can you try the master branch?

@jelly We probably should publish v1.0.0, or maybe include the latest commit into a new v1.0.1 release?

**Comment by Jolle99** [comment]
Hello, thanks for the fast updates, much appreciated.
Is there an automatic update available? If not, can you explain how to update manually please?

Thanks!

J.

**Comment by dagwieers** [comment]
@Jolle99 We have this documented for the VRT NU add-on here:
https://github.com/add-ons/plugin.video.vrt.nu/wiki/Updating#running-the-latest-development-branch-master-branch

**Comment by Jolle99** [comment]
Hello Dag,
I just installed the 1.0.0  but it's not working either. The "live stream" option doesn't show. It only shows the three dots.

J.

**Comment by fripsy** [comment]
Exactly the same problem as Jolle99 here, got the "Check credentials" message with v0.0.9, update from the master to v1.0.0 and now only have the 2 dots, no channel list... this is on a RPi 4 running LibreElec with Kodi 18.6.
On another device running Ubuntu 18.04 with Kodi 18.7, I still have the same error with v1.0.0 as with v0.0.9: Aanmelden mislukt.
The only error in the log is:
`ERROR: /home/frank/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning`
It clearly is a login issue on both devices, without any related errors in the logfile, even with Kodi debug enabled.
The strange thing is that it seems to be intermitted, Last week (with v0.0.9) I was unable to login. A few days later, without changing anything, it started working again, till yesterday...
Needless to say I did restart the 2 devices numerous times, but still no luck.
The credentials used work without a problem in FireFox and Chrome on different pc's running Ubuntu 20.04 and Mac OSX...
I guess this is going to be a hard one to crack...
I spent some time debuging the python code, but can't find any obvious reasons as to why the login won't work, my guess is it has something to do with the login/authorize sequence, perhaps some variables that are not passed correctly... but I'm only guessing...
Frank

**Comment by Jolle99** [comment]
On my Nvidia Shield box - Kodi 18.6, the Yelo v1.0.0. worked yesterday evening. It did NOT work on my Mac, Kodi 18.7 and Yelo v1.0.0. Didn't have time yet to test is on my Xiaomi Box.

**Comment by dagwieers** [comment]
I updated to Kodi v18.7 (LibreELEC v9.2.3) on my RPi and Yelo is still working as before.

I noticed that the Yelo add-on stores a `data.json` with a token, which is usually generated at login. I removed that file, and it generated it a new one on the next login. So at least for me the login process works fine without captcha as-is.

**Comment by Jolle99** [comment]
Tried again, Yelo only works on Nvidia Shield, not working on Mac, not working on Xiaomi. All three with Yelo v1.0.0 (installed add-on via zip-file)

**Comment by fripsy** [comment]
Well, I've been investigating a little more...
I added some logging to the code and I can see that **def _login(self)** is returning **https://login.prd.telenet.be/openid/login?authentication_error=true**, this clearly means the login has failed.
The url returned above displays a page with the (in)famous **reCaptcha**...
After examining what is happening in a browser when you login, I noticed a bunch of cookies that are not present in the the app...
So I added the links that were setting those cookies and tried again... nope, that doesn't work...
So someone needs to find out why some devices do work and others don't.
My guess is that if you reboot a device with a working app, the app will stop working...
Sadly I can't test this as none of my 4 devices running Kodi will start the Yelo app...

**Comment by Jolle99** [comment]
I rebooted my (working) Nvidia before reading Fripsy's update and Yelo still seems to be working.
But would need to have this working on my Xiaomi Box as well...

**Comment by fripsy** [comment]
Hmm, there goes my theory....

**Comment by fripsy** [comment]
Got it working on LibreElec now!
At first it wasn't working, I just got the 2 dots.
If I compared the files in .kodi/userdata/addon_data/plugin.video.yelo, there were a bunch of files probably left there from the previous version, I deleted them, restarted Yelo and... TADA !
It is working now with XML Simple IPTV and the guide...
But...
Some channels refuse to display, these channels, when opened in a normal browser, ask to register the device, which, obviously, Kodi can't ask... I perhaps open another issue for this as it is not related to this one.

**Comment by fripsy** [comment]
### Final conclusion:
If you get the 2 dots instead of the channel list, Kodi can not login at yeloplay.
If you are positive that your credentials are correct and you have an internet connection, **check your public IP address, this has to be in Belgium!**
If it is not, install a VPN with a Belgian IP.

**Comment by Jolle99** [comment]
That's not the case for me. With VPN it works on Nvidia, but not on Mac nor Xiaomi. All three with the latest Yelo version v1.0.0, Kodi 18.6 and 18.7 tested.

**Comment by fripsy** [comment]
My vpn only allows 1 connection at the time, perhaps yours does too?

**Comment by dagwieers** [comment]
I have not looked into this myself, but various content providers forbid the use of their services in their Terms of Use outside of a specific region where they have licensed the content. IIANM the EU mandates services to remain working within the EU, so this is mostly a problem outside of the EU.

A violation of the Terms of Use is a personal and wilful act.

**Comment by fripsy** [comment]
@dagwieers Yes this is true, however I'm in France and, although they are bit... french, it is still a part of Europe...
So I can watch Yelo perfectly in a browser, even without vpn, after I solve the reCaptCha.
So if this addon is used in Europe without a Belgian vpn, it won't work because it can't get passed the reCaptCha. If a Belgian vpn is used, there is no reCaptCha thus the addon works.
This is what is happening on my site, but the use of a Belgian vpn should work even if you are outside of Europe (if my theory is correct).

**Comment by dagwieers** [comment]
@fripsy I did not want to go into individual cases. My remark was mostly intended for readers passing by .

**Comment by timtilburgs** [comment]
> Got it working on LibreElec now!
> At first it wasn't working, I just got the 2 dots.
> If I compared the files in .kodi/userdata/addon_data/plugin.video.yelo, there were a bunch of files probably left there from the previous version, I deleted them, restarted Yelo and... TADA !
> It is working now with XML Simple IPTV and the guide...
> But...
> Some channels refuse to display, these channels, when opened in a normal browser, ask to register the device, which, obviously, Kodi can't ask... I perhaps open another issue for this as it is not related to this one.

@fripsy 
How do you setup the yelo channels in simple iptv, can you publish your xml file?

**Comment by fripsy** [comment]
@timtilburgs 
Sorry for the late replay, I'm abroad for the moment so can't check my system.
But, it should all be automatic, from the top of my head:
- install Yeloplay app
- install iptv-manager
- install simple iptv
- configure YeloPlay app
- run the YeloPlay app from addons, verify all is working
- open iptv manager and let iptv manager configure simple iptv
After that, the channels on YeloPlay should show up in the TV section, you can then alter the numbers etc. through the Kodi configuration.

As I mentioned, I write this from memory, so it could be a little off, but that is basically the setup.
It is important that you first start the YeloPlay app from within addons, to allow all cookies and keys to be downloaded and configured, after that all is kept in memory (on disk).

Cheers.

**Comment by shycoderX** [comment]
I just tried with Express VPN connected to US and France. When connected to France I do not experience any issues trying to watch the channel, so no reCaptCha.. In the US on the other hand I get the "You can only watch TV via tv-app in the EU.

Is this only with specific channels?

**Comment by fripsy** [comment]
@shycoderX 

Indeed, this is only with specific channels, some channels work from within the EU without a vpn, for other a Belgian vpn is needed.
For example, TF1 does not work over here without a Belgian vpn.

I guess this has to do with the rights Telenet has for diffusing the station.

**Comment by shycoderX** [comment]
> @shycoderX
> 
> Indeed, this is only with specific channels, some channels work from within the EU without a vpn, for other a Belgian vpn is needed.
> For example, TF1 does not work over here without a Belgian vpn.
> 
> I guess this has to do with the rights Telenet has for diffusing the station.

Yes you are right, but some of the later code changes has broken the message box showing you the reason why it couldn't play the stream.

[https://imgur.com/iclaCXu](url)

**Comment by fripsy** [comment]
**The url**

`https://api.yeloplay.be/api/v1/stream/start`

**The request**

`{"meta":{"schema":"stream/Stream.json","version":"4.1"},"stream":{"deviceId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","resource":{"watchMode":"Live","links":{"tvChannel":"bloomberg"},"timeShiftOffset":0},"context":"Watch-TV","platform":"Web","drmMethod":"WIDEVINE","protocol":"DASH"}}`

**The response**

`Status: 403`

`{
  "meta" : {
    "schema" : "common/Error.json",
    "version" : "4.1",
    "ttl" : 0
  },
  "errors" : [ {
    "id" : "39e96ddd-5916-4491-b1d6-306a6bfb849a",
    "code" : "EPG_RESTRICTED_BELGIUM",
    "title" : "Policy failure",
    "cause" : [ ]
  } ]
}`

The return status is also 403, the way it is coded now, it will always try to register the device instead of raising an error, my bad.

**Comment by peno64** [comment]
Just want to add something to this for people also having the issue that the addon says "check your credentials".
yelo play didn't work here either anymore, whatever I tried (uninstall completely, install from kodi repo, install latest version from here), nothing worked. It was some time ago that I used the addon. Then I came across this thread and I read about being abroad and vpn. Well I am in Bellgium, in my own house, but I do use a vpn (nordvpn) but also connected to a Belgium server. So I tried to disable the vpn and run the yello addon again and it worked immediately. Even when I then activate my vpn again, even if I restart my PI with the vpn active, it keeps on working now.
So the conclusion I have here is that when credentials are refreshed by yelo (cookie or whatever?) that you may not be connected via a vpn to have a succesfull login and once that you have it you can work again with a vpn probably because credentials are now cached for some time.

**Comment by Inloggedoe** [comment]
Hi peno64
I have exactly this problem, but I will not return to Belgium in the next months as i'm in Africa for a few months. So  I have my Telenet subscription and Nordvpn, set on Belgium, but could only login once. The next day my credentials were wrong... which of course is not correct as I can still login on the iPad, but not when using the firestick and kodi. Any suggestion or solution for this issue??

**Comment by peno64** [comment]
@Inloggedoe 
telenet most probably can detect dat you are connected via a vpn  and doesn't like this. Probably they have a list of known vpn providers and block all these. So the only way I see how to solve this is connect with an unknown vpn to telenet to Belgium.
I for example have a vpn on my router and can connect from anywhere to that vpn and then the connected device acts as if I am at home. I haven't tried that yet but I guess that would work... I don't see another way.

**Comment by Inloggedoe** [comment]
I have a separate router as well with Nordvpn  on it, but it’s still on its way as some luggage was delayed. I hope to see it in a few weeks and will definitely test this out. However what would be the difference with a vpn on a router and a vpn on the firestick for telenet?

**Comment by peno64** [comment]
Well but I don't mean that the router uses a vpn like nordvpn because then you will have the same problem. I mean that the router is a vpn provider to your own network. So from abroad you connect to the vpn of the router and then your abroad computer thinks and acts as he is at home. The internet will then also be as if it is connected to the telenet internet and not the one from abroad.
With nordvpn running on your router you will not accomplish this.

**Comment by Inloggedoe** [comment]
Hi

I am not that tech savvy to fully understand what you mean with your answer.

I can install a router in Belgium with a VPN on it, but how do I connect
from abroad to that specific router? (But probably this is not what you
wanted to explain me)

But another option I guess, and for me probably easier,  is to buy a
dedicated EU IP with NordVPN and than use that one on the firestick.

Or you think Telenet will block this as well?

Thanks anyway.



Op ma 5 okt. 2020 om 09:59 schreef peno64 <notifications@github.com>

**Comment by Brecht87** [comment]
Hi,

I've been trying to use the addon these past weeks in the EU where you should be able to logon and watch. Isn't a problem usually but I do get a "login failed"; my guess is due to a pesky Captcha you have to fill in to authenticate. I don't think you get that problem in Belgium. I tried a VPN connection but the captcha still appears when trying to logon through the app - and therefore I guess also in Kodi. In any case - it fails.

Is there a workaround for captchas? Thanks in advance!

**Comment by peno64** [comment]
@Inloggedoe 
I have NordVPN and when connected to that VPN, the telenet logon fails, even if I connect to a Belgium VPN. So telenet sees this also.

On my router I have dd-wrt, an open source firmware which replaces the router firmware. It has alot more functionalities than standard router firmware and one of them is to setup your router as a vpn. See following printscreen:

![image](https://user-images.githubusercontent.com/32430988/97551031-bf67a780-19d2-11eb-868a-4d88d602e0bd.png)

replace at the bottom user with a login name and password with a password.

And then you can connect to this vpn and it is as if you are at home.

**Comment by Inloggedoe** [comment]
Hi,

I have the same setup on one of my old routers (NordVPN installed with
ddwrt), but that router is still somewhere on the worlds oceans, hopefully
will arrive soon and then I can try it.

So, according to you that might work, even if the router is here in Africa?
(It did for TV Vlaanderen when we were out of the EU and wanted to use the
internet facilities, like recording and see program info) but as we now are
in a different country where TV Vlaanderen doesn’t reach the yelo app for
Kodi would be a good alternative, if I manage to get it working. (Strangely
it did for a few days in August, since then I get the message to check my
login... although on IOS all still works as before, only on the firestick I
get the error)

Let’s hope for the best.

Will keep you posted

Op do 29 okt. 2020 om 12:40 schreef peno64 <notifications@github.com>

**Comment by peno64** [comment]
The router has to be in Belgium connected to a telenet internet connection...

**Comment by Inloggedoe** [comment]
Hi

Thanks a lot for your reply and knowledge!

That’s what I actually thought as well, and then to work with dyndns I
suppose to get connected from here to my official home in Belgium (as this
is what I do to see the cctv from abroad).

Have to check my upload speed with Telenet then as the vpn will bring that
speed down as otherwise I will still not be able to see fluently from here.

Am wondering though if a static and dedicated IP (which I can buy from
NordVPN) in Holland would work, any idea on this?

Otherwise I will have to buy an Apple TV to stream from the iPad or a new
TV with Apple airplay2, but doubt that would be available here in the local
market...





Op do 29 okt. 2020 om 13:35 schreef peno64 <notifications@github.com>

**Comment by Brecht87** [comment]
So a dedicated private vpn server would be the only solution? Seems a bit overkill for a captcha?

@dagwieers , @fripsy , thanks for a great addon that kept on working until recently - is there really no other way?

**Comment by peno64** [comment]
call it a work-around instead of a solution

**Comment by Brecht87** [comment]
The strange thing is that I can logon and load all the channels; so I actually think I get past the captcha; but when I try to start a channel I get an error. In the log report that translates to:

```
2020-10-29 17:28:17.136 T:20696   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
2020-10-29 17:28:17.141 T:20696   DEBUG: CGUIWindowVideoBase::OnPlayMedia plugin://plugin.video.yelo/play/id/dicoveryhd
2020-10-29 17:28:17.143 T:20696   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Yelo('plugin://plugin.video.yelo/play/id/dicoveryhd','21','','resume:false')
2020-10-29 17:28:17.143 T:16248   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-10-29 17:28:17.143 T:16248    INFO: initializing python engine.
2020-10-29 17:28:17.143 T:16248   DEBUG: CPythonInvoker(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py): start processing
2020-10-29 17:28:17.164 T:3216   DEBUG: Thread scriptobs start, auto delete: false
2020-10-29 17:28:17.165 T:16248   DEBUG: -->Python Interpreter Initialized<--
2020-10-29 17:28:17.165 T:16248   DEBUG: CPythonInvoker(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py): the source file to load is "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py"
2020-10-29 17:28:17.165 T:16248   DEBUG: CPythonInvoker(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py): setting the Python path to C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.certifi\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.chardet\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.dateutil\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.idna\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.routing\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.six\lib;C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.urllib3\lib;C:\Program Files\Kodi\system\python\DLLs;C:\Program Files\Kodi\system\python\Lib;C:\Program Files\Kodi\python27.zip;C:\Program Files\Kodi\system\python\lib\plat-win;C:\Program Files\Kodi\system\python\lib\lib-tk;C:\Program Files\Kodi;C:\Program Files\Kodi\system\python;C:\Program Files\Kodi\system\python\lib\site-packages
2020-10-29 17:28:17.165 T:16248   DEBUG: CPythonInvoker(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py): entering source directory C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib
2020-10-29 17:28:17.165 T:16248   DEBUG: CPythonInvoker(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py): instantiating addon using automatically obtained id of "plugin.video.yelo" dependent on version 2.26.0 of the xbmc.python api
2020-10-29 17:28:17.325 T:16248   DEBUG: [plugin.video.yelo][routing] Dispatching to 'play_id', args: {u'channel_id': u'dicoveryhd'}
2020-10-29 17:28:17.364 T:20696   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-10-29 17:28:17.509 T:16248   ERROR: C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-10-29 17:28:17.569 T:16248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py", line 10, in <module>
                                                run(argv)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon.py", line 51, in run
                                                plugin.run(argv)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon.py", line 31, in play_id
                                                yelo.play(channel_id)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\yelo.py", line 30, in play
                                                manifest_url = self.get_manifest(channel)
                                              File "C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\yelo_api.py", line 270, in get_manifest
                                                stream_desc = stream.get('streamDescriptor')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2020-10-29 17:28:17.569 T:16248   DEBUG: CPythonInvoker::onExecutionDone(26, C:\Users\USERNAME\AppData\Roaming\Kodi\addons\plugin.video.yelo\resources\lib\addon_entry.py)
2020-10-29 17:28:17.571 T:20696   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-10-29 17:28:17.571 T:22464    INFO: CActiveAESink::OpenSink - initialize sink
2020-10-29 17:28:17.571 T:22464   DEBUG: CActiveAESink::OpenSink - trying to open device DIRECTSOUND:default
2020-10-29 17:28:17.592 T:22464   DEBUG: CAESinkDirectSound::Initialize: Using Window handle: 0x1d0bf8
2020-10-29 17:28:17.602 T:22464   DEBUG: CAESinkDirectSound::Initialize: secondary buffer created
2020-10-29 17:28:17.603 T:22464   DEBUG: CAESinkDirectSound::Initialize: Initializing DirectSound with the following parameters:
2020-10-29 17:28:17.603 T:22464   DEBUG:   Audio Device    : Hörlurar (Bose QC35 II Stereo)
2020-10-29 17:28:17.603 T:22464   DEBUG:   Sample Rate     : 44100
2020-10-29 17:28:17.603 T:22464   DEBUG:   Sample Format   : AE_FMT_FLOAT
2020-10-29 17:28:17.603 T:22464   DEBUG:   Bits Per Sample : 32
2020-10-29 17:28:17.603 T:22464   DEBUG:   Valid Bits/Samp : 32
2020-10-29 17:28:17.603 T:22464   DEBUG:   Channel Count   : 2
2020-10-29 17:28:17.603 T:22464   DEBUG:   Block Align     : 8
2020-10-29 17:28:17.603 T:22464   DEBUG:   Avg. Bytes Sec  : 352800
2020-10-29 17:28:17.603 T:22464   DEBUG:   Samples/Block   : 32
2020-10-29 17:28:17.603 T:22464   DEBUG:   Format cBSize   : 22
2020-10-29 17:28:17.603 T:22464   DEBUG:   Channel Layout  : FL, FR
2020-10-29 17:28:17.603 T:22464   DEBUG:   Channel Mask    : 3
2020-10-29 17:28:17.603 T:22464   DEBUG:   Frames          : 661
2020-10-29 17:28:17.603 T:22464   DEBUG:   Frame Size      : 8
2020-10-29 17:28:17.603 T:22464   DEBUG: CActiveAESink::OpenSink - DIRECTSOUND Initialized:
2020-10-29 17:28:17.603 T:22464   DEBUG:   Output Device : default
2020-10-29 17:28:17.603 T:22464   DEBUG:   Sample Rate   : 44100
2020-10-29 17:28:17.603 T:22464   DEBUG:   Sample Format : AE_FMT_FLOAT
2020-10-29 17:28:17.603 T:22464   DEBUG:   Channel Count : 2
2020-10-29 17:28:17.603 T:22464   DEBUG:   Channel Layout: FL, FR
2020-10-29 17:28:17.603 T:22464   DEBUG:   Frames        : 661
2020-10-29 17:28:17.603 T:22464   DEBUG:   Frame Size    : 8
2020-10-29 17:28:17.620 T:16248    INFO: Python interpreter stopped
2020-10-29 17:28:17.620 T:16248   DEBUG: Thread LanguageInvoker 16248 terminating
2020-10-29 17:28:17.622 T:3216   DEBUG: Thread scriptobs 3216 terminating
2020-10-29 17:28:17.636 T:20696   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-10-29 17:28:17.636 T:20696   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.yelo/play/id/dicoveryhd]
2020-10-29 17:28:17.636 T:20696   DEBUG: Playlist Player: no more playable items... aborting playback
2020-10-29 17:28:17.637 T:25152   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-10-29 17:28:17.666 T:8456   DEBUG: Thread JobWorker start, auto delete: true
2020-10-29 17:28:17.670 T:25152   DEBUG: Thread BackgroundLoader 25152 terminating
2020-10-29 17:28:17.952 T:22464   DEBUG: CAESinkDirectSound::CheckPlayStatus: Resuming Playback
2020-10-29 17:28:18.847 T:20696   DEBUG: Keyboard: scancode: 0x38, sym: 0x0134, unicode: 0x0000, modifier: 0x100
2020-10-29 17:28:18.847 T:20696   DEBUG: CInputManager::HandleKey: alt-long-leftalt (0x104f0d4) pressed, action is
2020-10-29 17:28:18.848 T:20696   DEBUG: ------ Window Deinit (Pointer.xml) ------

```

**Comment by Jolle99** [comment]
I've not followed this topic for a while, but I can confirm one of the above statements. 
I'm outside the EU and I couldn't login to the Yelo add-on (check credentials error), although I was on a ExpressVPN connection with a Belgian IP.
However, I now have a VPN connection to my Telenet router in Belgium (via OpenVPN) and then I can login on the Yelo add on with Kodi, so the captcha check is passed when you have a Telenet IP it seems.

**Comment by Inloggedoe** [comment]
Hi Jolle99

Good to see your work around actually works!

So may I ask you how you made the
‘VPN connection to my Telenet router in Belgium’

As, because of Covid, we will not return to Belgium very soon, I was
wondering the correct way to achieve this.

1/ Does the original Telenet router work with a vpn, so can you put
openvpn/NordVPN/... easily on that router or did you connect a separate
router with vpn on it to the Telenet one?

2/ Did you know how to do the whole procedure yourself (I suppose you have
to work with a dynamic dns or not?) or did you use a certain website with
all the explanation ‘how to’. Please share if it’s the latter.

Thanks!



Op zo 1 nov. 2020 om 13:34 schreef Jolle99 <notifications@github.com>

**Comment by Jolle99** [comment]
Not sure if this is the right topic for that but I have a Raspberry PI connected to the Telenet router and run a VPN on that device. Configuration can be done with this process (it's Dutch but there must be English versions online as well):
https://raspberrytips.nl/pivpn-de-eenvoudige-manier-om-openvpn-te-installeren/

**Comment by peno64** [comment]
@Jolle99 Is indeed also a possibility. Has the  same effect as having a vpn on the router as I described.

**Comment by peno64** [comment]
@Inloggedoe It  is for sure not  possible to put a vpn on the telenet router itself. We are not allowed to change much settings of the telenet router and this via the telenet webpages. I use a separate router next to the telenet router. In fact I use that router only to provide me internet and connect it to the digibox (because telenet only allows a direct internet connection to the digibox from their router and not from an own router after telenets router. All my other  internet connections, also wifi I all do via my own router.

**Comment by Inloggedoe** [comment]
@peno64

So, as a resume you have done following:

- ddwrt on own router
- add NordVPN credentials to it
- added dynamic dns (
https://www.howtogeek.com/66438/how-to-easily-access-your-home-network-from-anywhere-with-ddns/)
to the ddwrt setup
- connect it to Telenet router

-> done: access from everywhere to your home  network

Correct?




Op zo 1 nov. 2020 om 15:46 schreef peno64 <notifications@github.com>

**Comment by peno64** [comment]
@Inloggedoe No totally 
- ddwrt on the router and configure ddwrt that itself acts as a vpn and indded added a dynamic dns.
No other vpn service involved because then it will not work. the addon must see telenet and that is done via the vpn on the router, not via a 3rd party vpn which connects to another kond of internet.

**Comment by Inloggedoe** [comment]
Ok, got it! Thanks a lot for the whole explanation.

Unfortunately it will take a while before I’m back in Belgium due to the
Covid restrictions before I can set it up at my own house.

Hopefully the current Kodi add on might be working again before ;)

If not, I definitely try this work around!

Cheers









Op zo 1 nov. 2020 om 16:32 schreef peno64 <notifications@github.com>

**Comment by peno64** [comment]
I think the biggest problem will be that yelo will not be there anymore for a long time.
The new telenet digiboxes use another system *and* another app for which even no kodi addon doesn't exist yet...

**Comment by Inloggedoe** [comment]
Than it will be streaming from iPhone/iPad through Apple TV or Airplay 2...
or a hdmi from laptop to tv or a new Kodi addon!



Op zo 1 nov. 2020 om 18:59 schreef peno64 <notifications@github.com>

**Comment by Jolle99** [comment]
Where has that been announced? I'd love to have an AppleTV/AndroidTV app for Yelo. Although the Kodi add-on is a great alternative for now.

**Comment by peno64** [comment]
Is niet niet echt aangekondigd maar zoals je oa op https://www2.telenet.be/nl/klantenservice/yelo-app-downloaden/ kan zien is er nu naast de yelo app ook een telenet tv app en deze is enkel voor de laatste digicorders. Telenet kennende zullen ze dus die oude yelo app niet all te lang meer onderhouden en de vraag is dan maar als de nieuw tv app dan ook nog de oude digicoders zal supporteren. Nu in ieder geval niet. Je kan niet met uw yelo login inloggen op de nieuwe tv app en omgekeerd. En als de yelo app verdwijnt zal ook de kodi addon niet meer werken...
